# ---[ Default ]--------------------------------------
# 変更を反映するために /pack reload してください
# ----------------------------------------------------
# url: ""
# リソースパックのURL
# ----------------------------------------------------
# sha1: ""
# リソースパックのハッシュ値
# ----------------------------------------------------

url: ""
sha1: ""

use-join: true
use-plugin-message: false